### ISSUE TITLE
Adjust integer generation bounds

### ISSUE THREAD

**Issue by monsterkrampe** [JustinFeng/fakeit#12]
Assume that neither a minimum nor a maximum is set for an integer in the Api Specification.
fakeit currently generates a random integer in range `[1, 2**32]` in that case.
This would be roughly equivalent to an unsigned 32 Bit integer.

According to
https://swagger.io/docs/specification/data-models/data-types/#numbers
it seems like the integer type in Openapi has no bound at all unless a format is specified.

Since the common understanding of integer is a 32 Bit integer I think those bounds would also be fine as defaults.

Thus the default bounds for the integer generation could be `[-2**31, 2**31 - 1]`.

Little story how I stumbled upon this and how this affects me:
We currently develop an application there we are given a Backend and the API Spec for it.
We implement some kind of middleware in Java and a Frontend in Javascript for it.
For Development purpose we want to mock the Backend.
For the middleware we generate some Java code from the API Spec.

The Java generator treats `type: integer` even without a format specified as a normal 32 Bit signed Integer.
Thus in half of the cases the mock server generates numbers which are too big at the moment.

Actually I think that the Java Generator is wrong by assuming 32 Bit integers if no format is specified.
Nevertheless I'm not sure what a useful default behavior should look like, but I think that generating unsigned 32 Bit integers by default, might not be the best choice.
I would suggest creating either arbitrarily large signed integers (and support the format property) to match the Openapi Specification or to create signed 32 Bit integers by default for compatibility reasons (I don't know how other code generator treat integers by default but I tend to think, that it might be quite common to assume 32 Bit integers).

Let me know your thoughts on this @JustinFeng.

**Comment by JustinFeng** [comment]
Hey @monsterkrampe 

This is a very good suggestion, I searched a little bit about relevant specification and implementations, for example

- OpenAPI spec, as you have mentioned, there is no bound defined. However, it also comments on `int32` to be *commonly used integer type*
- `json-schema-faker` npm package, which is used by `prism`, defines the default integer range to be `[-100000000, 100000000]`

my idea on the dynamic data generation is always to cover the most useful data range, but not necessary to include every possible cases, which you can tell from default string, string date format, number, array length, etc.

So that I would go ahead with adopting `[-2**31, 2**31 - 1]` as the default range for integer and number. Again, thank you for the suggestion, this is a really good catch
