### ISSUE TITLE
Query parameter array

### ISSUE THREAD

**Issue by jordan-myob** [JustinFeng/fakeit#23]
**Context**
Sending arrays in query parameters don't have a standard. For example, sending an array of `Ids` can be done in the following formats:

- `?ids=1&ids=2&ids=3`
- `?ids[]=1&ids[]=2&ids[]=3`
- `?ids=1,2,3`

Choosing which format to go with usually depends on which language and framework is used and how it interprets it.

**Issue**
For our use case we have selected to use the format `?ids=1&ids=2&ids=3` because that is what works for .Net Core. For tests that sends an array of more than one item in the array `FakeIt` works perfectly as expected. However if an array of a single item is sent (`?ids=1`) `FakeIt` will interpret that as not sending an array but a single value and will return an error instead:
```
schema expected array, but received String
```

Interestingly, if we had used the format `?ids[]=1&ids[]=2&ids[]=3` and sent `?ids[]=1` that will work fine. I don't know if that's because ruby likes that format better or it's the validation library.

Thanks @JustinFeng!

**Comment by justinfeng-ap** [comment]
Hi @jordan-myob, so glad to hear from you, yep, i did notice that behavior, it's a ruby thing(actually rack), I will have a closer look to see whether I can coerse the parameter if the spec is expecting an array

Will let you know once I get something up, cheers man

**Comment by JustinFeng** [comment]
Hi @jordan-myob, so glad to hear from you, yep, i did notice that behavior, it's a ruby thing(actually rack), I will have a closer look to see whether I can coerse the parameter if the spec is expecting an array

Will let you know once I get something up, cheers man

**Comment by JustinFeng** [comment]
Hi @jordan-myob, I released 0.9.1 to support auto coercion query params to array when openapi schema is defined as an array. 

However, there is a limitation, the coercion will only happen for a query param defined directly under the `parameters` section of openapi spec, but not for the query param defined with a json `$ref`. It's because I only want to add this `smart` for a query param but not anything else like request body, but with the `openapi_parser` library I'm using now, I cannot tell the source if json `$ref` is in the way.

Please have a try and let me know if there is any question/issues, cheers man

**Comment by jordan-myob** [comment]
Amazing!! Thanks @JustinFeng, I'll give it a shot and let you know. I think that limitation makes perfect sense. I think we normally define it under the `parameters` section and not in a `$ref`.

**Comment by jordan-myob** [comment]
@JustinFeng just to let you know, this totally fixed the issue! Thank you ❤️
