### ISSUE TITLE
Request not completing

### ISSUE THREAD

**Issue by Tall-Paul** [JustinFeng/fakeit#3]
request for /claim/1 never completes as per earlier issue

I've attached the open api spec, nothing sensitive or secret in there.

[openapi.zip](https://github.com/JustinFeng/fakeit/files/3325813/openapi.zip)

_Originally posted by @Tall-Paul in https://github.com/JustinFeng/fakeit/issues/2#issuecomment-505478558_

**Comment by JustinFeng** [comment]
Thank you @Tall-Paul, I can reproduce the issue locally, it is definitely an issue about example generation.

**Comment by JustinFeng** [comment]
@Tall-Paul Figured out the reason for the hanging request, it caused by the random array item size. For the spec file you provided, as there are lots of array inside array scenario, fakeit ends up generating a HUGE response which behaves like it never completes. So I lowered the array size for performance concern.

Will release new version 0.1.4

**Comment by Tall-Paul** [comment]
Great, thanks Justin

**Comment by JustinFeng** [comment]
0.1.4 has been released, available in both ruby gem and docker image, please feel free to try it out

Thank you for your feedback
